# Generated by Django 3.0.2 on 2020-02-01 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200201_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 10, 13, 49, 452468)),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(null=True, upload_to='productimage'),
        ),
    ]
